### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by xTooth** [olavim/hy-forum#6]
# Koodikatselmointi

Projekti ladattu 30.9 kl 15.35

Projektisi on mielestäni loistavalla mallilla. Olet vissiin tehnyt jotain pythonilla/flaskilla aikasemminkin projektin rakenteesta päätellen.
Tässä kuitenkin muutama huomio jotka huomasin sovellusta kun testailin sovelluksen toimintaa. (moni ellei kaikki näistä asioista on varmasti jo työn alla)

- Jos yrittää tehdä käyttäjän jolla on sama nimi kuin jollain olemassa olevalla käyttäjällä handlataan tilanne ehkä hieman hupsusti, sivu vain ilmoittaa että "Error Something went wrong" ja formi käyttäjän luomiseen katoaa täysin.

- Toinen mielenkiintoinen huiomio on ettei herokuappi pyöri https tilassa vaan selain ilmoittaa ettei sivu ole turvallinen.

- Yksi kiva lisä toiminnallisuuteen olisi jos muokatuissa postauksissa olisi jonkun näköinen merkintä siitä että niitä on editoitu, tämä on helppo saada aikaan vertaamalla luonti ja muokkaus aikaa.

- Topic:ien editointi ei taida toimia toivotulla/ilmoitetulla tavalla. Uusi käyttäjä voi editoida mitä tahansa topic:ia. (ovatko kaikki käyttäjät toistaiseksi moderaattoreita / admineita)

- onko tuolla current time printillä joku ajatus? Jäi vähän epäselväksi miksi se tulostuu joka sivua tutkiessa, liittyykö johonkin debuggailuun ja unohtunut tuonne?

Projekti on selkeä rakenteeltaan vaikka onkin kurssilla opetettuun rakenteeseen nähden täysin erilainen. Itse koodikin on erittäin puhtaan oloista, en löytänyt  purkkaa tai muutenkaan outoja ratkaisuja. Luokat ja metodit sekä muuttujat ovat kaikki nimetty selvästi. Osa projektin rakenteesta menee kieltämättä minulla yli hilseen kun Python ei ole entuudestaan tuttua. Eli perjaatteessa kommentointia voisi olla enemmän, ihan vaan seuraavaa koodikatselmoijaa ajatellen.

Yleisesti ottaen kaikki tehdyksi merkatut ominaisuudet löytyvät, ja valtaosa niistä toimii toivotulla tavalla. Projektisi on selkeä ja vaikken kaikkea siitä ymmärrä koodia on helppo lukea.

**Comment by olavim** [comment]
Kiitos katselmoinnista.

> Toinen mielenkiintoinen huiomio on ettei herokuappi pyöri https tilassa vaan selain ilmoittaa ettei sivu ole turvallinen.

Outoa. Itselläni se pyörii kyllä https protokollassa ihan kiltisti, ja itseasiassa ohjaa automaattisesti https:ään, jos yritän yhdistää http:llä.

> Topic:ien editointi ei taida toimia toivotulla/ilmoitetulla tavalla. Uusi käyttäjä voi editoida mitä tahansa topic:ia. (ovatko kaikki käyttäjät toistaiseksi moderaattoreita / admineita)

Käyttäjien roolit ja oikeudet ovat tosiaan vasta työn alla, joten testailua varten kaikki ovat toistaiseksi moderaattoreita.

> onko tuolla current time printillä joku ajatus? Jäi vähän epäselväksi miksi se tulostuu joka sivua tutkiessa, liittyykö johonkin debuggailuun ja unohtunut tuonne?

Tarkoitat tuota "It is currently..." tekstiä sivun ylälaidassa? Se on pitkälti internet-foorumeille tyypillinen visuaalinen elementti. Perinteisesti käyttäjät voivat asettaa oman aikavyöhykkeensä, jolloin tämänhetkisen ajan ilmoittaminen käyttäjän aikavyöhykkeessä on hyödyllistä. Tätä käyttötarkoitusta ajan ilmoittaminen tässä projektissa ei kuitenkaan aja, sillä käyttäjät eivät voi asettaa omaa aikavyöhykettään.

Jos totta puhutaan niin mun mielestä se palkki näytti vähän hölmöltä ilman sitä aikaa.

> Osa projektin rakenteesta menee kieltämättä minulla yli hilseen kun Python ei ole entuudestaan tuttua.

Siellä on esimerkiksi tyylien muuntamista scss formaatista css formaattiin ja tietokantamigraatioita, jotka ovat kovassa äänessä tuolla `run.py`:ssä. Ne eivät tämän kurssin aiheisiin/vaatimuksiin kuitenkaan liity, niin niistä ei tarvitse koodikatselmoijana välittää. Ne nopeuttavat kehittämistä pidemmällä tähtäimellä, joten niihin tutustuminen on tietenkin hyödyllistä 😉 

> Yksi kiva lisä toiminnallisuuteen olisi jos muokatuissa postauksissa olisi jonkun näköinen merkintä siitä että niitä on editoitu, tämä on helppo saada aikaan vertaamalla luonti ja muokkaus aikaa.

Hyvä idea, luultavasti pääsee mukaan.

> Eli perjaatteessa kommentointia voisi olla enemmän, ihan vaan seuraavaa koodikatselmoijaa ajatellen.

Ehdottomasti.
