### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by ollim1** [olavim/hy-forum#7]
Haettu 19.31 12.10.2019
Sovelluksen ulkoasu on siisti ja yhtenäinen. Elementeissä saisi tosin olla ehkä hieman enemmän sisältöä täytettä kohden.

Sovellus täyttää user storyjen vaatimukset pääosin. Puutteita kuitenkin on: hakutoiminto on case-sensitive, enkä löytänyt sovelluksesta toiminnallisuutta oman viestiketjun nimen muokkaamiseen. 

Sovelluksen käytettävyys on hyvä. Käyttöliittymä on selkeä, ja sivujen rakentamisessa käytetään oikean tyyppisiä elementtejä. Toiminnasta ei yleisesti löydy moitittavaa. Käyttöoikeusjärjestelmä on hienosti toteutettu yksityiskohtaisine määrittelyineen, ja uusia käyttäjärooleja on helppoa rakentaa.

Koodissa on joitakin lieviä ongelmia. `__init__.py`-tiedostot eivät liene tarpeellisia kaikkialla, eikä kaiken tarvitse periä TimestampBasea. Tarvitseeko esimerkiksi käyttäjärooleista tallentaa viimeisintä muokkausaikaa?

Koodissa käytään paljon Pythonin kehittyneempiä ominaisuuksia koodin suoraviivaistamiseksi. Luokat on jäsennelty hyvin.

Sivupohjissa on koodin luettavuuden kannalta suositeltavaa käyttää sisennykseen sarkaimen sijaan kahta tai neljää välilyöntiä. Esimerkiksi useimmissa komentoriviympäristöissä yksi sarkain sisentää riviä oletusarvoisesti kahdeksan välilyönnin verran, mikä tekee erityisen syvälle sisentyneistä riveistä hyvin leveitä.

**Comment by olavim** [comment]
Kiitos katselmoinnista!

> hakutoiminto on case-sensitive

Tähän ei ole järkevää ratkaisua, kun pitää ottaa sqlite huomioon (en myöskään halua, että sovellus toimii eri tavalla riippuen tietokannasta). PostgreSQL tukee `ILIKE` operaattoria, mutta valitettavasti sqlitellä ei ole vastinetta. Sqlitellä ei myöskään voi tehdä full text hakuja.

> enkä löytänyt sovelluksesta toiminnallisuutta oman viestiketjun nimen muokkaamiseen.

Tämä on ihan design choice. Muiden käyttäjien on vaikeaa löytää viestiketju uudelleen, jos sen nimi voi muuttua helposti.

> `__init__.py`-tiedostot eivät liene tarpeellisia kaikkialla

On ne tarpeellisia kaikkialla missä ne tällä hetkellä ovat. Löysitkö jonkin paikan, missä ei olisi tarvinnut?

> eikä kaiken tarvitse periä TimestampBasea

Haluan `updated_at` ja `created_at` kentät kaikille tauluille riippumatta siitä, näkyykö ne käyttäjälle. Tämä helpottaa tietokannan hallinnointia ja käyttöä, sekä joidenkin ongelmatilanteiden debuggausta.

> Sivupohjissa on koodin luettavuuden kannalta suositeltavaa käyttää sisennykseen sarkaimen sijaan kahta tai neljää välilyöntiä

Tämä sarkaimet vs. välilyönnit keskustelu on pitkälti mielipideasia. Itse pidän sarkaimista.

Jos haluat argumentin miksi kaikkien pitäisi käyttää sarkaimia kaikessa koodissa (kunhan ohjelmointikieli sitä tukee), niin saavutettavuus. Kahdella huononäköisellä/näkövammaisella henkilöllä voi olla hyvinkin erilaiset vaatimukset, jotta koodia pystyy lukemaan. Toinen saattaa haluta katsella koodia jättimäisillä kirjaimilla, jolloin on järkevää, että sisennykset ovat hyvin pieniä. Toinen taas saattaa haluta katsella koodia siten, että sisennykset ovat erittäin selkeitä, vaikkapa 8-16 välilyöntiä. Molemmat pystyvät katsella koodia, joka käyttää sarkaimia, sillä sarkaimen leveyden pystyy yleensä työympäristössä muuttamaan.

Ainakin linuxilla komentorivin sarkainleveyden asettaminen on niinkin yksinkertaista kuin `tabs -4`.
